# Generated by Django 2.1.5 on 2019-02-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('display', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('display', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=80)),
                ('Sub_title', models.TextField()),
                ('back_drop', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('side_display', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('icon', models.CharField(choices=[('fas fa-laptop-code', 'Laptop'), ('fas fa-user', 'User'), ('fas fa-network-wired', 'Network'), ('fas fa-globe-america', 'Globe'), ('fas fa-layer-group', 'Layer'), ('fas fa-chart-pie', 'Pie Chart'), ('fas fa-chart-line', 'Line Chart')], max_length=80)),
                ('display', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
            ],
        ),
    ]
