# Generated by Django 2.1.5 on 2019-02-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Careers',
            new_name='Career',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
