# Generated by Django 2.1.5 on 2019-02-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190201_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='Sub_title',
            new_name='sub_title',
        ),
    ]
