# Generated by Django 2.1.5 on 2019-02-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190201_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='content_1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_2',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_3',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub_title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whyus',
            name='sub_title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
