# Generated by Django 2.1.5 on 2019-02-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190201_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='content',
            new_name='content_1',
        ),
        migrations.AddField(
            model_name='service',
            name='content_2',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='content_3',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='sub_title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
