# Generated by Django 2.1.5 on 2019-02-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190201_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='sub_header_1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sub_header_2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sub_header_3',
        ),
    ]
