# Generated by Django 2.1.5 on 2019-02-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20190201_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='sub_header_1',
        ),
    ]
