# Generated by Django 2.1.5 on 2019-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_service_sub_header_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sub_header_1',
            field=models.TextField(null=True),
        ),
    ]
