# Generated by Django 2.1.5 on 2019-02-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20190201_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sub_header_1',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
