# Generated by Django 2.1.5 on 2019-02-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20190201_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sub_title',
            field=models.CharField(max_length=400),
        ),
    ]
