# Generated by Django 2.1.5 on 2019-02-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20190201_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='content',
            new_name='content_1',
        ),
        migrations.AddField(
            model_name='career',
            name='content_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='sub_header_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='sub_header_2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
