# Generated by Django 2.1.5 on 2019-02-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20190202_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='section',
            field=models.CharField(default='main', editable=False, max_length=80),
        ),
    ]
