# Generated by Django 2.1.5 on 2019-02-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_main_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='section',
            field=models.CharField(default='About Us', editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='career',
            name='section',
            field=models.CharField(default='Careers', editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='whyus',
            name='section',
            field=models.CharField(default='Why Us', editable=False, max_length=80),
        ),
    ]
