# Generated by Django 2.1.5 on 2019-02-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20190202_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='Marketing_1', editable=False, max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marketing_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='Marketing_2', editable=False, max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='sub_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='content_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='content_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='sub_header_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='sub_header_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_header_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_header_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_header_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
