# Generated by Django 2.1.5 on 2019-02-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20190202_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='Banner 1', editable=False, max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='Banner 2', editable=False, max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Marketing_1',
        ),
        migrations.DeleteModel(
            name='Marketing_2',
        ),
    ]
