# Generated by Django 2.1.5 on 2019-02-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20190202_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner_1',
            new_name='Banner1',
        ),
        migrations.RenameModel(
            old_name='Banner_2',
            new_name='Banner2',
        ),
    ]
