# Generated by Django 2.1.5 on 2019-02-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20190202_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='content_3',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub_header_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub_header_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
