# Generated by Django 2.1.5 on 2019-02-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20190202_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUsMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='main', editable=False, max_length=80)),
                ('main_title', models.CharField(max_length=80)),
                ('sub_title', models.TextField()),
                ('back_drop', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('side_display', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
    ]
