# Generated by Django 2.1.5 on 2019-02-03 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_whyusmain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='banner1',
            options={'verbose_name_plural': 'Banner 1'},
        ),
        migrations.AlterModelOptions(
            name='banner2',
            options={'verbose_name_plural': 'Banner 2'},
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name_plural': 'Career'},
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name_plural': 'Main'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='whyus',
            options={'verbose_name_plural': 'WhyUs'},
        ),
        migrations.AlterModelOptions(
            name='whyusmain',
            options={'verbose_name_plural': 'Why Us Main'},
        ),
    ]
