# Generated by Django 2.1.5 on 2019-02-03 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20190203_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatwedo',
            name='side_display',
        ),
    ]
