# Generated by Django 2.1.5 on 2019-02-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20190203_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwedo',
            name='side_display',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
