# Generated by Django 2.1.5 on 2019-02-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_whatwedo_side_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img_1',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='service',
            name='img_2',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='service',
            name='img_3',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
