# Generated by Django 2.1.5 on 2019-02-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20190203_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img_text_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='img_text_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
