# Generated by Django 2.1.5 on 2019-02-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20190203_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='section',
        ),
        migrations.AddField(
            model_name='career',
            name='content_3',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='img_1',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='career',
            name='img_2',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='career',
            name='img_3',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='career',
            name='img_text_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='img_text_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='img_text_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='sub_header_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='sub_title',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='content_1',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='content_2',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='title',
            field=models.CharField(default='Why Us', editable=False, max_length=80),
        ),
    ]
