# Generated by Django 2.1.5 on 2019-02-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_career_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='Job ad', editable=False, max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('add', models.TextField()),
            ],
        ),
    ]
