# Generated by Django 2.1.5 on 2019-02-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_jobad'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobad',
            name='bullet_1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='bullet_2',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='bullet_3',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='bullet_4',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='bullet_5',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='second_bullet_1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='second_bullet_2',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='second_bullet_3',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='second_bullet_4',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='second_bullet_5',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='sub_header_1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='sub_header_2',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='section',
            field=models.CharField(default='Job Ad', editable=False, max_length=80),
        ),
    ]
