# Generated by Django 2.1.5 on 2019-02-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_auto_20190203_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobad',
            name='header',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
