# Generated by Django 2.1.5 on 2019-02-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_jobad_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobad',
            old_name='add',
            new_name='ad',
        ),
    ]
