# Generated by Django 2.1.5 on 2019-02-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_auto_20190203_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='sub_title',
        ),
    ]
