# Generated by Django 2.1.5 on 2019-02-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_remove_main_sub_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='tag_line',
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='tag_line',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
