# Generated by Django 2.1.5 on 2019-02-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_auto_20190203_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='tag_line',
        ),
        migrations.RemoveField(
            model_name='whatwedo',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='career',
            name='tag_line',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
