# Generated by Django 2.1.5 on 2019-02-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='img_1',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='img_3',
        ),
    ]
