# Generated by Django 2.1.5 on 2019-02-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_auto_20190205_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='section',
            field=models.CharField(default='Careers', editable=False, max_length=80),
        ),
    ]
