# Generated by Django 2.1.5 on 2019-02-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_auto_20190207_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='City', editable=False, max_length=80)),
                ('City', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
