# Generated by Django 2.1.5 on 2019-02-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='Apply', editable=False, max_length=80)),
                ('header', models.CharField(max_length=80, null=True)),
                ('City', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
