# Generated by Django 2.1.5 on 2019-02-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_auto_20190209_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'verbose_name_plural': 'Apply'},
        ),
    ]
