# Generated by Django 2.1.5 on 2019-02-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_auto_20190209_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='header',
        ),
        migrations.AddField(
            model_name='jobad',
            name='apply',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
