# Generated by Django 2.1.5 on 2019-02-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_auto_20190209_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='receiving_email',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
