# Generated by Django 2.1.5 on 2019-02-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0053_apply_receiving_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='sub_title',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
