# Generated by Django 2.1.5 on 2019-02-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0055_auto_20190212_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='side_display',
        ),
        migrations.RemoveField(
            model_name='main',
            name='tag_line',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='section',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='title',
        ),
    ]
