# Generated by Django 2.1.5 on 2019-02-16 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0056_auto_20190216_0601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhyUs',
        ),
    ]
