# Generated by Django 2.1.5 on 2019-03-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_delete_whyus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobad',
            name='sub_header_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
