# Generated by Django 2.1.5 on 2019-03-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0058_auto_20190326_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='ad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='apply',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='bullet_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='bullet_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='bullet_3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='bullet_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='bullet_5',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='header',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='second_bullet_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='second_bullet_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='second_bullet_3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='second_bullet_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='second_bullet_5',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='section',
            field=models.CharField(blank=True, default='Job Ad', editable=False, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='sub_header_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='sub_header_3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='third_bullet_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='third_bullet_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='third_bullet_3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
