# Generated by Django 2.1.5 on 2019-03-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0059_auto_20190326_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
