# Generated by Django 2.1.5 on 2019-03-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0060_auto_20190326_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='address_line_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='address_line_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='zip_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
