# Generated by Django 2.1.5 on 2019-03-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0061_auto_20190326_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='zip_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
